### ISSUE TITLE
Have getWindowSegments match the matchMedia api

### ISSUE THREAD

**Issue by Kilian** [webscreens/window-segments#14]
getWindowSegments() doesn't return a live value back, so the current solution for that is wrapping it in a `window.onresize` event to get live feedback.

The `window.matchMedia` api however can [attach a listener directly](https://polypane.app/blog/the-complete-guide-to-css-media-queries/#using-media-queries-in-javascript):

```js
const match = window.matchMedia('(min-width: 400px)');

match.addListener((e) => {
  if (e.matches) {
    /* do a thing */
  } else {
    /* do another thing */
  }
});
```

I would propose the getWindowSegments() should match the matchMedia api in this regard and similarly let users add an event listener with `addListener`. This will simplify code and it will make the api's more consistent.

**Comment by Kilian** [comment]
closing this because nothing is happening in this repository.

**Comment by anssiko** [comment]
@Kilian thanks for bringing this issue to our attention, and sorry for the delay. The group with @dlibby-'s lead is now evaluating the Visual Viewport API as a possible solution, as you seem to have discovered https://github.com/WICG/visual-viewport/issues/72

See the related vF2F discussion: https://www.w3.org/2021/02/24-webscreens-minutes.html#t03

See also https://webscreens.github.io/form-factors/ that attempts to document this landscape comprised of multiple specs at varying stages of standardization.
